version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cyberml-backend:latest
    container_name: cyberml-backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=CyberMLService;Username=root;Password=example
    depends_on:
      - postgres
      - cache
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: CyberMLService
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres-db:

networks:
  app-network:
    driver: bridge